"""empty message

Revision ID: 6002fb76de1b
Revises: 
Create Date: 2017-11-26 19:51:47.037000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6002fb76de1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DDC_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('begintime', sa.DateTime(), nullable=True),
    sa.Column('DDC_ID', sa.String(length=50), nullable=True),
    sa.Column('biaohao', sa.String(length=50), nullable=True),
    sa.Column('data', sa.String(length=50), nullable=True),
    sa.Column('consumption', sa.String(length=50), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=True),
    sa.Column('cmd1', sa.String(length=50), nullable=True),
    sa.Column('cmd2', sa.String(length=50), nullable=True),
    sa.Column('cmdall1', sa.String(length=50), nullable=True),
    sa.Column('cmdall2', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DDC_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('DDC_ID', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('biaohao', sa.String(length=50), nullable=True),
    sa.Column('flag1', sa.String(length=50), nullable=True),
    sa.Column('flag2', sa.String(length=50), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DDC_refresh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('DDC_ID', sa.String(length=50), nullable=True),
    sa.Column('biaohao', sa.String(length=50), nullable=True),
    sa.Column('data', sa.String(length=50), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=True),
    sa.Column('consumption', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DDC_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('DDC_ID', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zhuangtaizi', sa.String(length=50), nullable=True),
    sa.Column('mark1', sa.String(length=50), nullable=True),
    sa.Column('mark2', sa.String(length=50), nullable=True),
    sa.Column('sign', sa.String(length=50), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=10), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('DDC_ID', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('DDC_state')
    op.drop_table('DDC_refresh')
    op.drop_table('DDC_info')
    op.drop_table('DDC_data')
    # ### end Alembic commands ###
